### PR TITLE
Normalized slashes on Windows

### PR DESCRIPTION
**Pull request by webmozart**
This PR tries to fix #4 on a lower level.

@Big-Whoop @tgalopin Could you check whether the Windows build succeeds for this PR?

### CODE REVIEW

**Comment by tgalopin** [comment]
I'm on it :)

**Comment by tgalopin** [comment]
Working on it: https://gist.github.com/tgalopin/6e20e455033ecd60d74d

**Comment by temp** [comment]
@webmozart Result of your PR on Windows:
https://gist.github.com/temp/36334d663efdbc57b0b5

**Comment by webmozart** [comment]
@temp I just updated the PR, could you rerun?

**Comment by webmozart** [comment]
Seems like this works. :)

**Pull request merged**
