### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by Th3Mouk**
Hi @webmozart I propose to fix CI and then discuss on improvements like #19

### CODE REVIEW

**Comment by Th3Mouk** [comment]
@webmozart HHVM now only support Hack and not PHP, does it still make sense to support HHVM ?

**Comment by sanmai** [comment]
I'd vouch for no. Current HHVM does not work with Composer, so for a Composer package it makes not sense to support HHVM 3.30. This release _had_ long term support, ending in November 2019.

**Comment by sanmai** [comment]
@Th3Mouk would you be interested in a co-maintainer role for a fork?

**Comment by Th3Mouk** [comment]
@sanmai I don't think it's necessary because @webmozart is active but he probably need some help

**Comment by sanmai** [comment]
Fair enough. I this merges within, say, a month, I'll try to add GitHub Actions-based CI. This is not a big deal at all, just saying.

**Comment by martinssipenko** [comment]
This could be closed in favor of #24, @Ocramius will you close?

**Pull request closed without merging**
