### PR TITLE
Support running under `alpine` and `musl`-based environments: use `GLOB_BRACE` only when defined

### LINKED ISSUE #15: GLOB_BRACE not defined in Alpine
It looks like that `GLOB_BRACE` is not supported in Alpine Linux (see https://bugs.php.net/bug.php?id=72095).

This leads to the following warning

```
Warning: glob() expects parameter 2 to be integer, string given in /app/vendor/webmozart/glob/src/Iterator/GlobIterator.php on line 55
```

In the link above there is also a proposed workaround to avoid such a problem

### PR DESCRIPTION
**Pull request by Firehed**
Fixes #15

### CODE REVIEW

**Comment by Firehed** [comment]
I saw an equivalent linked PR that stated tests need to run on Alpine too. I'll look into it.

**Review by Ocramius — APPROVED** [review]
LGTM :+1:

**Comment by Ocramius** [comment]
Excellent work, @Firehed! Thanks!

**Comment by stof** [comment]
what happens for globs which are using braces ?

**Comment by Ocramius** [comment]
@stof you'll have to be more specific about that, I fear. Perhaps issue outlining the potential problem?

**Comment by stof** [comment]
The support for alpine is "added" here by skipping the `GLOB_BRACE` constant. But this means that any glob pattern which actually uses braces (and so justify passing `GLOB_BRACE` to enable support for them) won't work on alpine

**Pull request merged**
