### PR TITLE
Add gitattributes, skip bundling build artifacts in released package 

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi,

Seems like this project is missing `.gitattributes` file so I tried to add one.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Thanks @VincentLanglet!

**Comment by dmitryuk** [comment]
@VincentLanglet do you remember why composer.lock file has not been ignored same way?

Our CVE tool Trivy scan all composer.lock files in `vendor` directory and found a lot of issues

**Comment by VincentLanglet** [comment]
I would say first that the CVE tool is wrong to scan the composer.lock in the vendor folder since it's not used when you install a library.

Also I often add the lock file in the gitignore file rather than just the gitattributes ; but you can still provide a pr to add it in the gitattributes if you want to

**Comment by Ocramius** [comment]
From a library PoV, working with unlocked dependencies has proven to be a long-term disaster, especially since libraries like Symfony straight out lie about supported dependency ranges :scream:

**Pull request merged**
